<script setup lang="ts">
import { ref } from 'vue';
import axios from 'axios';

const isLoading = ref(false);

const loginWithLine = async () => {
  isLoading.value = true;
  try {
    // 1. Fetch authorization URL generated by Django endpoint
    const response = await axios.get('http://localhost:8000/api/accounts/auth/line/login/');

    // 2. Redirect user to LINE's authorization page
    if (response.data.auth_url) {
      window.location.href = response.data.auth_url;
    }
  } catch (error) {
    console.error('Failed to initiate LINE login:', error);
    alert('Unable to connect to LINE login. Please try again.');
  } finally {
    isLoading.value = false;
  }
};
</script>

<template>
  <button class="line-btn" :disabled="isLoading" @click="loginWithLine">
    <!-- LINE Logo Icon -->
    <svg class="line-icon" viewBox="0 0 24 24" fill="currentColor">
      <path
        d="M12 2C6.48 2 2 5.8 2 10.48c0 2.87 1.78 5.4 4.54 7.01-.2.74-.72 2.68-.83 3.09-.13.52.19.51.4.37.16-.11 2.53-1.72 3.56-2.42.76.11 1.54.17 2.33.17 5.52 0 10-3.8 10-8.48S17.52 2 12 2z"
      />
    </svg>
    <span>{{ isLoading ? 'Connecting...' : 'Log in with LINE' }}</span>
  </button>
</template>

<style scoped>
.line-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 10px;
  background-color: #06c755; /* Official LINE Green */
  color: #ffffff;
  font-weight: 600;
  font-size: 15px;
  border: none;
  border-radius: 8px;
  padding: 12px 24px;
  cursor: pointer;
  transition:
    background-color 0.2s ease,
    transform 0.1s ease;
  width: 100%;
  max-width: 280px;
}

.line-btn:hover:not(:disabled) {
  background-color: #05b34c;
}

.line-btn:active:not(:disabled) {
  transform: scale(0.98);
}

.line-btn:disabled {
  opacity: 0.7;
  cursor: not-allowed;
}

.line-icon {
  width: 22px;
  height: 22px;
}
</style>
